version: 0.2


env:
  secrets-manager:
    AWSid: CodeBuild-cloudfront-extensions:access_key_id
    AWSkey: CodeBuild-cloudfront-extensions:secret_access_key
    GHToken: CodeBuild-cloudfront-extensions:oatuh_token

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws configure set aws_access_key_id $AWSid
      - aws configure set aws_secret_access_key $AWSkey
      - aws configure set default.region us-east-1
      - echo "install finished."
  pre_build:
    commands:
      - ls scripts/
      - ./scripts/set-label-name.sh
      - env
