version: 0.2


phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "install finished."
  pre_build:
    commands:
      - export labelName=${{ github.event.label.name }}
      - ./scripts/python-ci-content-scan.sh
