version: 0.2


phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "install finished."
  pre_build:
    commands:
      - export labelName=python
      - ./scripts/python-ci-content-scan.sh 
