version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "add-security-headers-cff"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8dzry4lo4z5o"
s3_prefix = "add-security-headers-cff"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
